name: CI/CD Pipeline

# Déclenchement du Workflow
on: 
  push : 
    branches: [master]
  pull_request: 
    branches: [master]


jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Récuperer le code du projet
        uses: actions/checkout@v4

      - name: Installer Nodejs
        uses: actions/setup-node@v4
    


      - name: Installer dépendances
        run: npm install


      - name: Lancer les test unitaires
        run: npm run test:unit

      - name: Lancer les test d'intégration
        run: npm run test:integration

      - name: Installer les navigateurs Playwright
        run: npx playwright install --with-deps
        
      - name:   Lancer les tests e2e
        run: npm run test:e2e

      
      - name: Déclencher le déploiement
        if: success()
        run: curl -X "${{secret_RENDER_DEPLOY_HOOK_URL}}"


